name: marl
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2026.5.14
  - expat=2.8.1
  - ld_impl_linux-64=2.44
  - libexpat=2.8.1
  - libffi=3.4.8
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libstdcxx=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.2
  - ncurses=6.5
  - openssl=3.5.7
  - packaging=26.0
  - pip=26.1.2
  - pthread-stubs=0.3
  - python=3.12.0
  - readline=8.3
  - sqlite=3.53.2
  - tk=8.6.15
  - tzdata=2026b
  - wheel=0.47.0
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.8.2
  - zlib=1.3.2
  - pip:
      - absl-py==2.4.0
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - attrs==26.1.0
      - cachebox==5.2.3
      - certifi==2026.6.17
      - charset-normalizer==3.4.7
      - click==8.4.2
      - cloudpickle==3.1.2
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - cuda-toolkit==13.0.2
      - deepdiff==9.1.0
      - dm-env==1.6
      - dm-env-rpc==1.1.7
      - dm-tree==0.1.10
      - docker-pycreds==0.4.0
      - enum34==1.1.10
      - filelock==3.29.0
      - fsspec==2026.4.0
      - gitdb==4.0.12
      - gitpython==3.1.50
      - googleapis-common-protos==1.73.0
      - grpcio==1.81.1
      - gym==0.26.2
      - gym-notices==0.1.0
      - idna==3.18
      - immutabledict==4.3.1
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mock==5.2.0
      - mpmath==1.3.0
      - mpyq==0.2.5
      - networkx==3.6.1
      - numpy==2.4.4
      - nvidia-cublas==13.1.1.3
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cudnn-cu13==9.20.0.48
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.1
      - nvidia-nccl-cu13==2.29.7
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - onpolicy==0.1.0
      - orderly-set==5.5.0
      - pillow==12.2.0
      - platformdirs==4.10.0
      - portpicker==1.6.0
      - protobuf==3.20.3
      - psutil==7.2.2
      - pydantic==2.13.4
      - pydantic-core==2.46.4
      - pygame==2.6.1
      - pysc2==4.0.0
      - pyyaml==6.0.3
      - requests==2.34.2
      - s2clientprotocol==5.0.16.97364.0
      - s2protocol==5.0.16.97364.0
      - scipy==1.18.0
      - sentry-sdk==2.63.0
      - setproctitle==1.3.7
      - setuptools==70.2.0
      - six==1.17.0
      - sk-video==1.1.10
      - smac==1.0.0
      - smacv2==1.0.0
      - smmap==5.0.3
      - sympy==1.14.0
      - tensorboardx==2.6.5
      - torch==2.12.1+cu130
      - torchaudio==2.11.0+cu130
      - torchvision==0.27.1+cu130
      - triton==3.7.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.7.0
      - wandb==0.17.9
      - websocket-client==1.9.0
      - wrapt==2.2.2
